// Initially setting the both left and right images value to default value of 6

function predictWinner() {
    // generating a random number for left image
    let randNumber1 = Math.floor((Math.random() * 6) + 1);

    // putting source of the left image to dice image as generated by random number
    document.querySelector('.img1').setAttribute("src", "./images/dice" + randNumber1 + ".png");

    // doing same for the right image as well
    let randNumber2 = Math.floor((Math.random() * 6) + 1);
    document.querySelector('.img2').setAttribute("src", "./images/dice" + randNumber2 + ".png");

    // logic to decide whihc player is the winner
    let winnerObj = document.querySelector('.container h1');
    if (randNumber1 > randNumber2) {
        winnerObj.innerHTML = "🚩 Player 1 Wins!";
    }
    else if (randNumber1 < randNumber2) {
        winnerObj.innerHTML = "Player 2 Wins! 🚩";
    }
    else {
        winnerObj.innerHTML = "It's a Draw!"
    }

}

